A = input("Masukkan Huruf")
B = input("Masukkan Huruf")
C = input("Masukkan Huruf")
D = input("Masukkan Huruf")
E = input("Masukkan Huruf")
F = input("Masukkan Huruf")
G = input("Masukkan Huruf")
H = input("Masukkan Huruf")
I = input("Masukkan Huruf")
J = input("Masukkan Huruf")
K = input("Masukkan Huruf")
L = input("Masukkan Huruf")
M = input("Masukkan Huruf")
N = input("Masukkan Huruf")
O = input("Masukkan Huruf")

print("Data 1", A,B,C,D,E,F,G,H,I,J,L,M,N,O)
